# baseURL = "https://your_domain.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "ACH PROCK"
# copyright = "Copy, _right?_ :thinking_face:"

theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  # name = "Your name here"
  headline = "Owner-operated residential rental property business collecting rent and managing rental property."
  # image = "img/author.jpg"  # path relative to static directory

  links = [
    { email = "mailto:achprocllc@andrewprock.com" },
    #{ pokerstove = { href = "http://www.pokerstove.com/" }},
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/andrewprock" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/andrewcprock" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    { linkedin = "https://linkedin.com/in/aprock" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/andrewprock" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
